//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp7.Databases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantHallsDatabaseEntities : DbContext
    {
        public RestaurantHallsDatabaseEntities()
            : base("name=RestaurantHallsDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Зал> Зал { get; set; }
        public virtual DbSet<ЗалСтол> ЗалСтол { get; set; }
        public virtual DbSet<Стол> Стол { get; set; }
    }
}
