//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp7.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗалСтол
    {
        public int КодЗала { get; set; }
        public int КодСтола { get; set; }
        public int КоординатаX { get; set; }
        public int КоординатаY { get; set; }
        public Nullable<bool> Диагональ { get; set; }
    
        public virtual Зал Зал { get; set; }
        public virtual Стол Стол { get; set; }
    }
}
