//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp7.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Стол
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Стол()
        {
            this.ЗалСтол = new HashSet<ЗалСтол>();
        }
    
        public int Код { get; set; }
        public string Наименование { get; set; }
        public byte ФормаСтола { get; set; }
        public bool Статус { get; set; }
        public byte КоличествоПерсон { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЗалСтол> ЗалСтол { get; set; }
    }
}
